### ISSUE TITLE
"Lookahead exceeds token buffer length" with simple grammar

### ISSUE THREAD

**Issue by Leandros** [jsinger67/parol#54] opened 2023-01-05 20:40 UTC
Trying to parse anything with a parser generated from this elementary grammar:

```
%start Foo
%title "Foo grammar"
%comment "Empty grammar generated by `parol`"
%line_comment "//"

%%

Rjs: 'Hello' 'world';
```

Trying to parse 

```
Hello world
```

results in the following errors:

```
  × Failed parsing file ./test.txt
  ├─▶ Failed accessing lookahead token!
  ╰─▶ Lookahead exceeds token buffer length
```

The error can be fixed by adding the empty case to the production:

```
Rjs: 'Hello' 'world' | ;
```

Is this intended behavior?

**Comment by jsinger67** [comment] 2023-01-06 05:52
@Leandros Thank you for reporting this.
I know about this behavior but it is not good documented and actually easy to fix.
The cause of this is that your first grammar ia actually k0. This results in a lookahead buffer of size 0.
I think I will fix this simply by setting the lower size limit of the lookahead buffer to 1.

**Comment by jsinger67** [comment] 2023-01-10 18:00
Fixed with commit c302ba2.

**Closed by jsinger67** 2023-01-10 18:00 UTC
Labels: bug

**Comment by Leandros** [comment] 2023-01-10 20:25
Wonderful. Thank you!
